#
# To startup things, just
#   docker-compose up

version: '2'
services:

  locomail:
    build: .
    ports:
      - "5000:5000"
      - "25:25"
    container_name: locomail
    image: viatorinc/locomail
